新增 註冊登入頁 & 個人資訊輸入頁面
DolceTseng/iRun pull request #12
Opened 2024-09-13 03:12 UTC by DolceTseng

> 怕太多要修改先上來一部份 🥲

* 進場動畫頁 & 立即開始/會員登入頁 會換成 Jeffery 版本的。
* 出生年份的下拉選單本地測好像會噴出畫面，我再看看怎麼修 qq

2024-09-13 03:14 UTC, DolceTseng commented on assets/images/LOGO.svg
我後來才發現原來這張我忘了傳到 dev ，所以到時候重覆的話再刪掉。

2024-09-13 03:29 UTC, DolceTseng commented on layout/login/date-sex.ejs
> +            </select>
我本地看下拉選單會超出去畫面外，先放著晚點再來修。
![{06480C63-B34D-450C-9C4B-9DFE140A5D0D}](https://github.com/user-attachments/assets/8826f8b8-4b8e-4b1d-8eb6-6e92fddf85fe)

2024-09-13 03:30 UTC, DolceTseng commented on layout/login/login-index.ejs
這頁會換 Jeffery 的

2024-09-13 03:30 UTC, DolceTseng commented on layout/login/splash.ejs
這頁也會換 Jeffery 的

2024-09-13 07:20 UTC, DolceTseng commented on layout/login/user-login.ejs
>                  <div class="hr-text mb-4">
加上了 fw-regular (font-weight: 400)

2024-09-13 08:59 UTC, DolceTseng commented on layout/login/frequency.ejs
* 運動頻率頁面完成

2024-09-13 09:03 UTC, DolceTseng commented on pages/login/frequency.html
運動頻率頁面完成

2024-09-13 09:04 UTC, DolceTseng commented on layout/login/coach-traits.ejs
ai 教練特質頁面完成

2024-09-16 16:47 UTC, Beginneraboutlife116 requested changes

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on assets/scss/pages/login/_user-login.scss
> +}
這邊汙染到全域的 img 了，所以首頁的 img 改變了
![截圖 2024-09-16 晚上11 37 36](https://github.com/user-attachments/assets/8ec28f31-4b91-491c-b1e4-818e3287b066)

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on pages/index.html
這邊感覺可以協助調整置中，目前看起來不會置中

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/nickname.ejs
> +            <a href="#" class="login-a p-6 me-4"><h6 class="text-secondary-300 fw-bold">返回</h6></a>
這邊可以補上到 `index.html` 的 route 了，應該是這樣：
```
href="../../pages/index.html"
```

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/nickname.ejs
> +            <input type="text" name="nickname" id="nickname" placeholder="請輸入名稱" class="form-control rounded-2">
可填加 `fw-regular` 使 font-weight 為 400

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/nickname.ejs
> +            <input type="text" name="nickname" id="nickname" placeholder="請輸入名稱" class="form-control rounded-2">
可以使用 `text-secondary-800`，`$input-plaintext-color` 沒有起到作用的樣子

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/nickname.ejs
> +            <a href="bodyinfo.html"  class="btn btn-irun rounded-4 fs-4 fw-bold text-white mb-8 flex-grow-1">下一步</a>
這邊可能會需要再麻煩加上 py-5，那時候 `btn-irun` 的設定只有處理樣式，沒有改 padding 的空間，再麻煩了

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/date-sex.ejs
> +            <select class="form-select rounded-2 mb-8" aria-label="">
字體顏色應該會是 secondary-800 的顏色

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/frequency.ejs
> +                <label class="btn btn-outline-irun d-flex flex-column align-items-center justify-content-center rounded-4 mb-4 login-text fw-regular">初階：沒有運動習慣</label>
checked 後 font-weight 應該是 bold (700)

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/frequency.ejs
> +                <label class="btn btn-outline-irun d-flex flex-column align-items-center justify-content-center rounded-4 mb-4 login-text fw-regular">初階：沒有運動習慣</label>
```
layout/login/coach-traits.ejs
```

也可能會需要這樣的調整

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/ai-coach.ejs
> +            <p class="text-center text-secondary-300 fs-7 fw-bold mb-0">只要幾步驟 開始屬於你的 AI 運動計畫</p>
這段話可能會需要刪除

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/ai-coach.ejs
> +            <img src="/assets/images/aicoach.png" alt="ai-coach" class="login-coach">
與下方會有一個 16px 的距離

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/ai-coach.ejs
> +                <p class="fs-7 fw-regular text-primary-700">HI，我是Micheal！<br>你的專屬AI教練<br>我推薦你<span class="fw-bold">先從150步頻</span><br><span class="fw-bold">每天20分鐘</span>開始訓練</p>
p 會有預設的 margin-bottom ，可以把它取消掉

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/login-index.ejs
這段需要刪除嗎？

2024-09-16 16:47 UTC, Beginneraboutlife116 commented on layout/login/user-login.ejs
> +                <h5 class="fw-bold text-primary-500 mb-4">會員登入</h5>
有些大標是用 line-height: 1.4 ，可以看一下，有必要的話，可以使用 `.lh-base` 來處理

2024-09-17 04:58 UTC, DolceTseng commented on layout/login/login-index.ejs
因為跟 Jeffery 的重覆了，不過我後來想想就放著XD

2024-09-17 12:34 UTC, Beginneraboutlife116 requested changes

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on pages/index.html
> +          <a href="./login/user-login.html" class="btn btn-outline-irun rounded-pill fs-6 py-6 w-100">會員登入</a>
font-size 應該是 20px，所以應該使用 `fs-4`
這邊不知道是不是後來設計有再改，因為我那邊原本也是 `fs-6`

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/nickname.ejs
> +            <label for="nickname" class="h5 fw-bold text-primary-500 mb- lh-base">如何稱呼</label>
margin-bottom 不見了

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on pages/login/index.html
這一個頁面是不是不會用到？

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on pages/login/login.html
這一個頁面是不是也到不了？
感覺沒有 link 可以到這邊

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/splash.ejs
是不是也用不到？

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/login-index.ejs
是不是用不到這一個？

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/coach-traits.ejs
> +            </div>
被選取時的顏色看設計稿是 primary-500 的 #15ADC5，跟前一個 frequency 有一點不同。

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/coach-traits.ejs
> +            </div>
另外，這邊的 `login-col` 與 `mb-4` 與 Bootstrap 的 格線系統 的 `gx-2`, `gy-4` 是一樣效果的，是因為什麼原因不用 BS 的做法呢（純粹好奇）

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/ai-coach.ejs
> +</div>
這段還有需要嗎？還是還沒設定好？皆可幫忙

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/user-login.ejs
> +                        <input type="email" name="login" id="email" placeholder="電子信箱" class="form-control rounded-2">
fw-regular 跟 text-secondary-800 會需要補一下

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/user-login.ejs
> +                        <input type="password" name="login" id="password" placeholder="密碼" class="form-control rounded-2">
同上

2024-09-17 12:34 UTC, Beginneraboutlife116 commented on layout/login/user-login.ejs
> +                    <label for="email" class="col-auto fs-6 fw-bold text-seconddary-800 mb-0 pe-4">帳號</label>
應該為 text-secondary-800，多打了 d

2024-09-17 14:16 UTC, DolceTseng commented on pages/login/index.html
對唷，我把他刪掉好了。

2024-09-17 14:19 UTC, DolceTseng commented on layout/login/coach-traits.ejs
> +            </div>
應該是當時在試別的東西，後來就沒想到要改回來

2024-09-17 14:30 UTC, CloveTseng commented on layout/login/ai-coach.ejs
> +</div>
這段不用了xd本來是在試做 placeholder，不小心推上去。

2024-09-17 15:38 UTC, Beginneraboutlife116 requested changes

2024-09-17 15:38 UTC, Beginneraboutlife116 commented on layout/login/user-login.ejs
>                      <label for="password" class="col-auto fs-6 fw-bold text-seconddary-800 mb-0 pe-4">密碼</label>
未修改到 secondary 的拼字問題

2024-09-17 15:38 UTC, Beginneraboutlife116 commented on layout/login/coach-traits.ejs
把 `gx-2`, `gy-4` 加在 `col` 上造成了 「最多可選三個」與 多選 的欄位空間變成了 32px。
應該是把 `gx-2`, `gy-4` 加在 `row` 上，可參考 Bootstrap 的文件：https://getbootstrap.com/docs/5.3/layout/gutters/
其實也很像是 `column-gap`, `row-gap` 的做法，所以這邊的問題需要解決：
![截圖 2024-09-17 晚上11 37 24](https://github.com/user-attachments/assets/bdab7670-1217-42ef-b7b3-3c308c826a6f)

2024-09-17 15:41 UTC, DolceTseng commented on layout/login/user-login.ejs
>                      <label for="password" class="col-auto fs-6 fw-bold text-seconddary-800 mb-0 pe-4">密碼</label>
oh sorry, 我沒注意。

2024-09-17 16:10 UTC, Beginneraboutlife116 approved these changes

2024-09-17 16:10 UTC, merged