頁面新增: 進入畫面 主頁面 設定 新手教學 開始運動
DolceTseng/iRun pull request #14
Opened 2024-09-14 01:15 UTC by a41522001

目前進度到GO畫面
![螢幕擷取畫面 2024-09-14 091348](https://github.com/user-attachments/assets/f7951544-f557-4027-8c6b-9c9e991aacce)

2024-09-14 01:28 UTC, a41522001 commented on assets/scss/all.scss
新增4隻頁面的scss檔 刪除原有的./pages/home/home-record

2024-09-14 01:30 UTC, a41522001 commented on assets/scss/all.scss
新增4隻頁面scss檔 刪除原有的./pages/home/home-record
![螢幕擷取畫面 2024-09-14 093023](https://github.com/user-attachments/assets/f87194f4-b53b-427c-8760-25867ab7a7a3)

2024-09-14 01:32 UTC, a41522001 commented on assets/images/icons/thumb-up.svg
更改為白色
![image](https://github.com/user-attachments/assets/618fe797-d7d8-4438-b1eb-937938d70d7d)

2024-09-14 01:32 UTC, a41522001 commented on assets/images/avatar2.png
新增avatar
![image](https://github.com/user-attachments/assets/1f0009a9-5d42-4185-a99f-9d3f334c79c7)

2024-09-14 01:33 UTC, a41522001 commented on assets/images/avatar1.png
新增avatar
![image](https://github.com/user-attachments/assets/24597256-9992-46da-905e-d0ccfad7fb0e)

2024-09-14 01:34 UTC, a41522001 commented on pages/index.html
更改標題 導覽列排版
![image](https://github.com/user-attachments/assets/4780198d-57cb-4ec5-b961-fcedc82207e9)

2024-09-15 06:18 UTC, Beginneraboutlife116 requested changes

2024-09-15 06:18 UTC, Beginneraboutlife116 commented on assets/scss/all.scss
>  @import "./pages/home/home-record";
這邊看起來未刪除到，可能需要看一下 local 那邊是否刪除了？

2024-09-15 06:18 UTC, Beginneraboutlife116 commented on pages/sport/index.html
> +      </div>
感覺可以這樣試試看
```
<div class="dropdown">
  <button class="btn btn-outline-secondary-300 text-secondary-800 fw-regular dropdown-toggle rounded-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
    顯示全部
  </button>
  <ul class="dropdown-menu py-0 rounded-2 border-secondary-300">
    <li class=""><a class="dropdown-item active rounded-top-2 p-3 fw-regular" href="#">顯示全部</a></li>
    <li><a class="dropdown-item p-3 fw-regular text-secondary-800 border-top border-secondary-300" href="./sport-chart.html">時長</a></li>
    <li><a class="dropdown-item p-3 fw-regular text-secondary-800 border-top border-secondary-300" href="./sport-chart.html">距離</a></li>
    <li><a class="dropdown-item p-3 fw-regular text-secondary-800 border-top border-secondary-300" href="./sport-chart.html">卡路里</a></li>
  </ul>
</div>
```
chart 那邊也可以這樣用

2024-09-15 06:18 UTC, Beginneraboutlife116 commented on pages/sport/sport-chart.html
> +      <ul class="list-unstyled mb-8 d-flex justify-content-between">
應該加 `align-items-center` 就可以了

2024-09-15 09:35 UTC, closed without merging